### PR TITLE
Adding the ability to index sitemaps by year

### PR DESCRIPTION
**Pull request by bcampeau**
This pull request enables sites to have multiple sitemap indexes by year. To enable, simply filter `msm_sitemap_index_by_year` to `true`.

Once enabled, instead of adding a single entry to robots.txt, you will see multiple entries like:
```
Sitemap: http://yourdomain.com/sitemap-2015.xml
Sitemap: http://yourdomain.com/sitemap-2016.xml
Sitemap: http://yourdomain.com/sitemap-2017.xml
```

Each sitemap will then contain all of the daily sitemap URLs for that particular year. Note the URL format for the daily sitemaps will change slightly. For example:
```
http://dev.nypost.com/sitemap-2017.xml?mm=06&dd=13
```

The format of the individual daily sitemaps remains unchanged.

Please note that when enabling or disabling this filter, you will need to flush rewrite rules since the URL format of the sitemap index changes. I considered making this an admin dashboard option so rewrite rules could be purged automatically but eventually decided this was too dangerous to be a checkbox. If someone is changing this filter, they should know what they're doing and purge rewrite rules as part of the deployment process.

This also adds unit tests for the new functionality and some minor code formatting and escaping cleanup.

### CODE REVIEW

**Comment by mjangda** [comment]
Out of curiosity, what's the reason for this change? Should it just be the default?

**Comment by bcampeau** [comment]
@mjangda test failure seems to be:

```
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /tmp/wordpress-tests-lib/includes/testcase.php on line 15
```

Can you kick it to run again and see if it still fails? Usually that clears up.

**Comment by pkevan** [comment]
> Can you kick it to run again and see if it still fails? Usually that clears up.

I've set it off again.

**Comment by bcampeau** [comment]
Hm, still failing in the same place in the core unit test code.

**Comment by mjangda** [comment]
We need to update the Travis config to use an older version of phpunit. Will take care of it.

**Comment by mjangda** [comment]
Fixed tests in #120. Rebasing with master should fix the tests here too.

**Comment by bcampeau** [comment]
Just rebased to re-run tests.

**Comment by bcampeau** [comment]
Just wanted to check and see where we think this might be on the roadmap for deployment.

Thanks!

**Comment by pkevan** [comment]
@bcampeau it's not been tested yet, but I'm hoping to take a look at this next week.  

I'll follow up when I've done it.

**Comment by pkevan** [comment]
@bcampeau any thoughts on making the resulting XML better formatted, i.e. the XML source has line breaks, so that debugging through wmt is easier?

**Pull request merged**
