### PR TITLE
Unit Test update to resolve run time and concerns with current logic

### PR DESCRIPTION
**Pull request by mdbitz**
https://github.com/Automattic/msm-sitemap/issues/92  Contains full details on the changes that are made as part of this Pull Request.

1) Updated Test Suite logic to call sitemap generation directly for post dates, instead of repetitively executing scheduled cron jobs.

2) Updated Date manipulations to use date() function instead of manually modifying  the day by 1.

3) Updated timestamp format to match msm-sitemap logic for xml comparison.

4) Removal of extraneous logic and variables that were not being utilized by tests.

5) PHPCS cleanup of the files to align with WordPress Standards.

### CODE REVIEW

**Comment by mdbitz** [comment]
Removed unused $build_dates variable and logic based on review by Stéphane Boisvert.

**Comment by mdbitz** [comment]
Above commits add new Testing around the following areas.

1) Static functions of Metro_Sitemap to validate they perform functionality as expected.

2) Validate Metro_Sitemap supports Custom Post Types

3) Validate Cron Jobs are scheduled and processed as expected.

**Comment by mjangda** [comment]
Nice improvements, @mdbitz! Some notes:

1) I wonder if we can make use of the `WP_UnitTestCase` factory methods for creating the dummy posts. That might simplify things a fair bit: http://wordpress.stackexchange.com/questions/139128/where-can-i-find-documentation-for-the-wp-unittestcase-factory-classes
2) We should rebase against master (which should fix the failing test).

**Comment by mjangda** [comment]
> I wonder if we can make use of the WP_UnitTestCase factory methods for creating the dummy posts.

Forgot to note: we can/should probably do this in a separate PR. Let's get the Travis greenlight on this and merge for now.

**Comment by mdbitz** [comment]
Latest update pulls in recent changes from the main repository as well as updates to 1 of the unit tests to align with date format changes in #101.

**Pull request merged**
