### PR TITLE
Added fiter for xml builder

### PR DESCRIPTION
**Pull request by umbrella-kirill-starikov**
We have errors with the sitemap, due to the presence of of "&amp" string in the links. For this reason, we want to be able to apply a filter to all XML document.

Example: /sitemap.xml?yyyy=2015&amp ;mm=12&amp ;dd=24

### CODE REVIEW

**Comment by mjangda** [comment]
Where are the errors coming from?

`&` needs to be encoded in sitemaps otherwise it's not valid XML (see http://xml.silmaril.ie/specials.html and http://stackoverflow.com/questions/1328538/how-do-i-escape-ampersands-in-xml)

**Comment by mjangda** [comment]
Examples (using this validator http://codebeautify.org/xmlvalidate):

`&` not encoded fails with `Error on->  Line :3 Column :40 Message :EntityRef: expecting ';'`:

```
<?xml version="1.0" encoding="UTF-8"?>
<sitemap>
    <loc>https://example.com/?foo=1&bar=1</loc>
</sitemap>
```

`&` encoded as `&amp;` validates:

```
<?xml version="1.0" encoding="UTF-8"?>
<sitemap>
    <loc>https://example.com/?foo=1&amp;bar=1</loc>
</sitemap>
```

**Comment by umbrella-kirill-starikov** [comment]
Hello Mohammad.
Errors coming from google wmt.
We want replace the `&amp;` on the & and add CDATA
Example: 
```
<?xml version="1.0" encoding="UTF-8"?>
<sitemap>
   <loc>
       <![CDATA[https://example.com/?foo=1&bar=1]]>
   </loc>
</sitemap>
```

**Comment by mjangda** [comment]
The sitemap protocol does not require CDATA tags: http://www.sitemaps.org/protocol.html

Rather than patching around the issue, it would be better to figure out why Webmaster Tools is throwing errors for a perfectly valid sitemap.

**Comment by umbrella-kirill-starikov** [comment]
CDATA (character data) is not a tag. A CDATA section contains text that will NOT be parsed by a parser.
Sitemap render links with `&amp;`


Google create request for url with `&amp;` for example `http://stylecaster.com/sitemap.xml?yyyy=2016&amp;mm=03&amp;dd=09`. 

This request returns a server error, because of the absence of the desired Sitemap.

**Comment by mjangda** [comment]
@david-binda has been working on a workaround on the VIP side to handle the URLs with encoded ampersands (which is a better fix than changing the output of the sitemap). Please follow up in a ticket to enable the workaround for your site.

**Pull request closed without merging**
