### PR TITLE
Issue 110

### PR DESCRIPTION
**Pull request by systemseven**
I've switched the generation to generate serialized data. Then that get's formatted on the front end with SimpleXML so we retain the benefits and abilities of using that. 

Performance wise your inserts/generation should be unaffected. (Or if it is affected, it's only marginal). We're still inserting text data but it's not formatted as XML anymore

The front end render seems to be okay, the default 500 page limit is around .002 seconds to render and if we up that to 5000 it's around .04 seconds to render.

### CODE REVIEW

**Comment by mjangda** [comment]
Thanks for taking the initial pass at this.

With the updated approach here, how do we handle this scenario that I noted in #110?

> What happens if the URL structure changes? How do we get other related data like the post modified date from just the URL?

It would also be good to do more thorough benchmarks with a really large scale dataset (e.g. for a site with 100K+ posts, does that change the measurements at all?) and ideally include details on how you're measuring as well.

**Comment by systemseven** [comment]
Hey!

Can you clarify the "what happens if the URL changes?"
Meaning the site map URL structure or the posts URL structure?

For other related data the site map generator has access to the whole post
object (I'm not storing just post urls like I originally stated) so if we
wanted extra data we could get it when we generate the sitemap.
Does that answer your question?

I'm running a script now to drop 100k posts into the DB. Will rerun my
tests and provide more data on how I'm testing when it's done.

Thanks!
Justin

**Comment by mjangda** [comment]
> Can you clarify the "what happens if the URL changes?" Meaning the site map URL structure or the posts URL structure?

The posts URL structure. Example: going from `/2017/01/post-name/` to `/category/post-name/`.

> For other related data the site map generator has access to the whole post
object (I'm not storing just post urls like I originally stated) so if we
wanted extra data we could get it when we generate the sitemap.

How would someone hooking into this filter (https://github.com/Automattic/msm-sitemap/pull/116/files#diff-67d63994628dd99d09072eee489c7487R706) access the post object? Previously, we were running the filter in The Loop, so you could access the global post object.

**Comment by systemseven** [comment]
I think after looking at this, that 1 fix could solve both things. So rather than just put an array of strings that are specific to the sitemap in the database (ie: loc, url, etc...) I can serialize the whole post object. 

That way when it's popped back out, I could pass it as a parameter to the `apply_filters` callback. 

The other way this helps is with generating the link at runtime. So rather than write the permalink to the DB we can get the permalink at runtime on the sitemap. Since we have the whole post object, we can pass it to `get_permalink()` and it should NOT run another DB query according to what I've read 

Thoughts here?

**Pull request closed without merging**
